"use client";

import { FormEvent, useEffect, useState } from "react";
import { Breadcrumb } from "@/components/ui/Breadcrumb";
import { Button } from "@/components/ui/Button";
import { Input, Select, Textarea } from "@/components/ui/Input";
import { formatINR } from "@/lib/utils";

type Product = { id: string; name: string; slug: string; price: number; makingCharge: number; inStock: boolean; category: string; goldPurity: string; image: string; description: string };
type Overview = { stats: { orders: number; contacts: number; designRequests: number; users: number; revenue: number }; orders: { orderId: string; customerName: string; phone: string; email: string; address: { address: string; city: string; state: string; pincode: string; country: string }; total: number; paymentStatus: string; currentStepIndex: number }[]; contacts: { id: string; name: string; email: string; message: string; status?: string }[]; designRequests: { id: string; fullName: string; jewelleryType: string; createdAt: string; status?: string }[]; users: { id: string; name: string; email: string; phone: string; role: string }[] };
const steps = ["Order Placed", "Order Confirmed", "Payment Confirmed", "Jewellery in Making", "Quality Check", "Ready for Delivery", "Delivered"];

export default function AdminPage() {
  const [data, setData] = useState<Overview | null>(null); const [products, setProducts] = useState<Product[]>([]); const [tab, setTab] = useState<string>("overview"); const [error, setError] = useState(""); const [notice, setNotice] = useState("");
  const [gold, setGold] = useState({ city: "Coimbatore", k24: "15317", k22: "14040", k18: "11810" });
  const [newProduct, setNewProduct] = useState({ name: "", price: "", makingCharge: "", category: "Rings", goldPurity: "22K", description: "" });
  async function load() { const [overviewResponse, productResponse] = await Promise.all([fetch("/api/admin/overview"), fetch("/api/admin/products")]); const overview = await overviewResponse.json(); const productData = await productResponse.json(); if (!overviewResponse.ok) setError(overview.error); else { setData(overview); setProducts(productData.products ?? []); } }
  useEffect(() => { const timer = window.setTimeout(() => { void load(); }, 0); return () => window.clearTimeout(timer); }, []);
  async function updateOrder(orderId: string, currentStepIndex: number) { const response = await fetch(`/api/admin/orders/${orderId}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ currentStepIndex }) }); if (response.ok) { setNotice("Order status updated"); load(); } }
  async function addProduct(event: FormEvent) { event.preventDefault(); const response = await fetch("/api/admin/products", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(newProduct) }); if (response.ok) { setNewProduct({ name: "", price: "", makingCharge: "", category: "Rings", goldPurity: "22K", description: "" }); setNotice("Product added"); load(); } else setError((await response.json()).error); }
  async function toggleStock(product: Product) { const response = await fetch(`/api/admin/products/${product.id}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ inStock: !product.inStock }) }); if (response.ok) load(); }
  async function deleteProduct(id: string) { if (!window.confirm("Delete this product?")) return; const response = await fetch(`/api/admin/products/${id}`, { method: "DELETE" }); if (response.ok) { setNotice("Product deleted"); load(); } }
  async function saveGold(event: FormEvent) { event.preventDefault(); const response = await fetch("/api/admin/gold-rate", { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ city: gold.city, rates: [{ purity: "24K", ratePerGram: Number(gold.k24) }, { purity: "22K", ratePerGram: Number(gold.k22) }, { purity: "18K", ratePerGram: Number(gold.k18) }] }) }); if (response.ok) setNotice("Gold rates updated"); }
  async function updateRequest(type: "contact" | "design", id: string, status: string) { const response = await fetch(`/api/admin/requests/${type}/${id}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ status }) }); if (response.ok) { setNotice("Request status updated"); load(); } }
  if (error) return <div className="container-page py-16 text-red-700">{error}</div>;
  if (!data) return <div className="container-page py-16">Loading…</div>;
  if (tab === "customers") return <div className="container-page py-10"><Breadcrumb items={[{ label: "Home", href: "/" }, { label: "Admin", href: "/admin" }, { label: "Customers" }]} /><h1 className="font-display text-3xl text-maroon-900 mt-4 mb-6">Customers ({data.users.filter((user) => user.role === "CUSTOMER").length})</h1><div className="border border-ink-300/25 bg-cream-100 p-5 flex flex-col gap-2">{data.users.filter((user) => user.role === "CUSTOMER").map((user) => <div key={user.id} className="flex justify-between border-b border-ink-300/20 py-3 text-sm"><span><strong>{user.name}</strong><br /><span className="text-ink-500">{user.email} · {user.phone || "No phone"}</span></span><span className="text-xs text-ink-500">Customer</span></div>)}</div></div>;
  if (tab === "requests") return <div className="container-page py-10"><Breadcrumb items={[{ label: "Home", href: "/" }, { label: "Admin", href: "/admin" }, { label: "Requests" }]} /><h1 className="font-display text-3xl text-maroon-900 mt-4 mb-6">Customer Requests</h1><div className="grid lg:grid-cols-2 gap-6"><section className="border border-ink-300/25 bg-cream-100 p-5"><h2 className="font-display text-xl text-maroon-900 mb-4">Contact Messages</h2>{data.contacts.map((item) => <div key={item.id} className="border-b border-ink-300/20 py-3 text-sm"><strong>{item.name}</strong><p className="text-ink-600 mb-2">{item.message}</p><Select value={item.status ?? "NEW"} onChange={(event) => updateRequest("contact", item.id, event.target.value)}><option>NEW</option><option>IN_PROGRESS</option><option>RESOLVED</option><option>REJECTED</option></Select></div>)}</section><section className="border border-ink-300/25 bg-cream-100 p-5"><h2 className="font-display text-xl text-maroon-900 mb-4">Custom Design Requests</h2>{data.designRequests.map((item) => <div key={item.id} className="border-b border-ink-300/20 py-3 text-sm"><strong>{item.id} · {item.fullName}</strong><p className="text-ink-600 mb-2">{item.jewelleryType}</p><Select value={item.status ?? "NEW"} onChange={(event) => updateRequest("design", item.id, event.target.value)}><option>NEW</option><option>IN_PROGRESS</option><option>RESOLVED</option><option>REJECTED</option></Select></div>)}</section></div></div>;
  return <div className="container-page py-10"><Breadcrumb items={[{ label: "Home", href: "/" }, { label: "Admin" }]} /><div className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between mt-4 mb-6"><div><p className="eyebrow text-gold-600">SRA Jewellers</p><h1 className="font-display text-3xl text-maroon-900">Admin Dashboard</h1></div><div className="flex flex-wrap gap-2"><Button size="sm" variant={tab === "overview" ? "primary" : "outline"} onClick={() => setTab("overview")}>Overview</Button><Button size="sm" variant={tab === "products" ? "primary" : "outline"} onClick={() => setTab("products")}>Products</Button><Button size="sm" variant={tab === "customers" ? "primary" : "outline"} onClick={() => setTab("customers")}>Customers</Button><Button size="sm" variant={tab === "requests" ? "primary" : "outline"} onClick={() => setTab("requests")}>Requests</Button><Button size="sm" variant={tab === "gold" ? "primary" : "outline"} onClick={() => setTab("gold")}>Gold Rate</Button></div></div>{notice && <p className="mb-4 text-sm text-emerald-700">{notice}</p>}
    {tab === "overview" && <><div className="grid sm:grid-cols-2 lg:grid-cols-5 gap-3 mb-8">{Object.entries(data.stats).map(([label, value]) => <div key={label} className="border border-ink-300/25 bg-cream-100 p-4"><p className="text-xs uppercase text-ink-500">{label}</p><p className="font-display text-2xl text-maroon-900 mt-1">{label === "revenue" ? formatINR(value) : value}</p></div>)}</div><section className="border border-ink-300/25 bg-cream-100 p-5"><h2 className="font-display text-xl text-maroon-900 mb-4">Orders &amp; Status</h2>{data.orders.length === 0 ? <p className="text-sm text-ink-500">No orders yet.</p> : <div className="flex flex-col gap-2">{data.orders.map((order) => <div key={order.orderId} className="flex flex-col gap-2 border-b border-ink-300/20 py-3 text-sm sm:flex-row sm:items-center sm:justify-between"><span><strong>{order.orderId}</strong> · {order.customerName}<br /><span className="text-xs text-ink-500">{formatINR(order.total)} · {order.paymentStatus}</span></span><Select aria-label={`Status for ${order.orderId}`} value={order.currentStepIndex} onChange={(event) => updateOrder(order.orderId, Number(event.target.value))} className="sm:max-w-xs">{steps.map((step, index) => <option key={step} value={index}>{step}</option>)}</Select></div>)}</div>}</section><section className="grid lg:grid-cols-2 gap-6 mt-6"><div className="border border-ink-300/25 bg-cream-100 p-5"><h2 className="font-display text-xl text-maroon-900 mb-3">Contact Messages</h2>{data.contacts.map((item) => <div key={item.id} className="border-b border-ink-300/20 py-2 text-sm"><strong>{item.name}</strong> · {item.email}<p className="text-ink-600">{item.message}</p></div>)}</div><div className="border border-ink-300/25 bg-cream-100 p-5"><h2 className="font-display text-xl text-maroon-900 mb-3">Design Requests</h2>{data.designRequests.map((item) => <div key={item.id} className="border-b border-ink-300/20 py-2 text-sm"><strong>{item.id}</strong> · {item.fullName}<p className="text-ink-600">{item.jewelleryType}</p></div>)}</div></section></>}
    {tab === "products" && <div className="grid lg:grid-cols-[360px_1fr] gap-6"><form onSubmit={addProduct} className="border border-ink-300/25 bg-cream-100 p-5 flex flex-col gap-3"><h2 className="font-display text-xl text-maroon-900">Add Product</h2><Input label="Product Name" value={newProduct.name} onChange={(e) => setNewProduct({ ...newProduct, name: e.target.value })} required /><Input label="Price" type="number" value={newProduct.price} onChange={(e) => setNewProduct({ ...newProduct, price: e.target.value })} required /><Input label="Making Charge" type="number" value={newProduct.makingCharge} onChange={(e) => setNewProduct({ ...newProduct, makingCharge: e.target.value })} required /><Select label="Category" value={newProduct.category} onChange={(e) => setNewProduct({ ...newProduct, category: e.target.value })}><option>Rings</option><option>Earrings</option><option>Necklaces</option><option>Chains</option><option>Bangles</option><option>Bracelets</option><option>Pendants</option><option>Bridal Jewellery</option></Select><Select label="Purity" value={newProduct.goldPurity} onChange={(e) => setNewProduct({ ...newProduct, goldPurity: e.target.value })}><option>18K</option><option>22K</option><option>24K</option></Select><Textarea label="Description" value={newProduct.description} onChange={(e) => setNewProduct({ ...newProduct, description: e.target.value })} /><Button type="submit">Add Product</Button></form><div className="border border-ink-300/25 bg-cream-100 p-5"><h2 className="font-display text-xl text-maroon-900 mb-4">Catalog ({products.length})</h2><div className="flex flex-col gap-2">{products.map((product) => <div key={product.id} className="flex flex-col gap-2 border-b border-ink-300/20 py-3 sm:flex-row sm:items-center sm:justify-between"><span><strong>{product.name}</strong><br /><span className="text-xs text-ink-500">{product.id} · {formatINR(product.price)} · {product.inStock ? "In stock" : "Out of stock"}</span></span><span className="flex gap-2"><Button size="sm" variant="outline" onClick={() => toggleStock(product)}>{product.inStock ? "Disable" : "Enable"}</Button><Button size="sm" variant="outline" onClick={() => deleteProduct(product.id)}>Delete</Button></span></div>)}</div></div></div>}
    {tab === "gold" && <form onSubmit={saveGold} className="max-w-xl border border-ink-300/25 bg-cream-100 p-6 flex flex-col gap-4"><h2 className="font-display text-xl text-maroon-900">Manage Gold Rate</h2><Input label="City" value={gold.city} onChange={(e) => setGold({ ...gold, city: e.target.value })} /><Input label="24K Rate / gram" type="number" value={gold.k24} onChange={(e) => setGold({ ...gold, k24: e.target.value })} /><Input label="22K Rate / gram" type="number" value={gold.k22} onChange={(e) => setGold({ ...gold, k22: e.target.value })} /><Input label="18K Rate / gram" type="number" value={gold.k18} onChange={(e) => setGold({ ...gold, k18: e.target.value })} /><Button type="submit">Save Gold Rates</Button></form>}
  </div>;
}
